Role can not depend on collection.
Workarounding this:

    sh-5.0$ rm -rf ~/.ansible/roles/linux-system-roles.storage/
    sh-5.0$ ansible-galaxy role install -r requirements.yml -vvv
    [DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with Ansible 2.12. Current version: 3.7.9 (default, Aug 19 2020, 17:05:11)
    [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]. This feature will be removed from ansible-core in version 2.12. Deprecation warnings can be disabled by setting
    deprecation_warnings=False in ansible.cfg.
    ansible-galaxy [core 2.11.7]
      config file = /home/jenkins/workspace/ContPerf70/ansible.cfg
      configured module search path = ['/home/jenkins/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
      ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
      ansible collection location = /home/jenkins/.ansible/collections:/usr/share/ansible/collections
      executable location = /usr/local/bin/ansible-galaxy
      python version = 3.7.9 (default, Aug 19 2020, 17:05:11) [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]
      jinja version = 3.0.3
      libyaml = True
    Using /home/jenkins/workspace/ContPerf70/ansible.cfg as config file
    [DEPRECATION WARNING]: [defaults]callback_whitelist option, normalizing names to new standard, use callbacks_enabled instead. This feature will be removed from ansible-
    core in version 2.15. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
    Reading requirement file at '/home/jenkins/workspace/ContPerf70/requirements.yml'
    found role {'name': 'linux-system-roles.storage', 'version': '', 'scm': None} in yaml file
    Opened /home/jenkins/.ansible/galaxy_token
    Starting galaxy role install process
    Processing role linux-system-roles.storage
    - downloading role 'storage', owned by linux-system-roles
    - downloading role from https://github.com/linux-system-roles/storage/archive/1.7.0.tar.gz
    - extracting linux-system-roles.storage to /home/jenkins/.ansible/roles/linux-system-roles.storage
    - linux-system-roles.storage (1.7.0) was installed successfully
    ERROR! Unexpected Exception, this is probably a bug: can only concatenate list (not "dict") to list
    the full traceback was:

    Traceback (most recent call last):
      File "/usr/local/bin/ansible-galaxy", line 135, in <module>
        exit_code = cli.run()
      File "/usr/local/lib/python3.7/site-packages/ansible/cli/galaxy.py", line 552, in run
        return context.CLIARGS['func']()
      File "/usr/local/lib/python3.7/site-packages/ansible/cli/galaxy.py", line 75, in method_wrapper
        return wrapped_method(*args, **kwargs)
      File "/usr/local/lib/python3.7/site-packages/ansible/cli/galaxy.py", line 1180, in execute_install
        self._execute_install_role(role_requirements)
      File "/usr/local/lib/python3.7/site-packages/ansible/cli/galaxy.py", line 1265, in _execute_install_role
        role_dependencies = (role.metadata.get('dependencies') or []) + role.requirements
    TypeError: can only concatenate list (not "dict") to list